name: 🚀 Feature Request
description: Suggest a new feature or enhancement for AutoLlama
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your use case.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: Briefly describe the feature you're requesting
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation and Use Case
      description: Why would this feature be useful? What problem does it solve?
      placeholder: |
        Describe the problem you're trying to solve or the workflow you'd like to improve.
        Include specific examples of how you would use this feature.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Describe your ideal solution:
        - What would the user interface look like?
        - How would the API work?
        - What would the user workflow be?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of AutoLlama would this feature affect?
      options:
        - Web Interface (React Frontend)
        - API Server (Node.js)
        - Document Processing Pipeline
        - Search & Retrieval
        - OpenWebUI Integration
        - Database Schema
        - Configuration/Settings
        - Documentation
        - DevOps/Deployment
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my use of AutoLlama)
        - High (Would significantly improve my workflow)
        - Medium (Nice to have improvement)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        - Other ways to solve this problem
        - Existing features that partially address this
        - External tools or integrations you've tried

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        If you have technical ideas about implementation:
        - API endpoints that might be needed
        - Database changes required
        - Dependencies that might be useful
        - Similar features in other tools

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the feature request
      placeholder: |
        - Mockups or screenshots
        - Links to similar features in other tools
        - Technical specifications
        - Performance considerations

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to submit a pull request for this feature
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I can provide ongoing feedback during development

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have clearly described the problem this feature would solve
          required: true
        - label: I have provided a detailed use case
          required: true
        - label: This feature aligns with AutoLlama's mission of contextual RAG
          required: true