version: '3.8'

services:
  marketing-homepage:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3004:80"
    restart: unless-stopped
    networks:
      - caddy_default
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  caddy_default:
    external: true