version: '3.8'

services:
  marketing-homepage:
    image: nginx:alpine
    ports:
      - "3004:80"
    restart: unless-stopped
    networks:
      - caddy2_default
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./assets:/usr/share/nginx/html/assets:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  caddy2_default:
    external: true